const homeRestaurantsData = [
  {
    id: "01",
    image: require("../../../assets/restaurantsHome/card1.jpg"),
    name: "Heaven's Food",
    rating: 4,
    requiredTime: "25-30mins",
    howCostly: "$$",
    category: "hamburger",
  },
  {
    id: "02",
    image: require("../../../assets/restaurantsHome/card2.jpg"),
    name: "Chill Out Mirpur",
    rating: 5,
    requiredTime: "10-15mins",
    howCostly: "$",
    category: "pizza",
  },
  {
    id: "03",
    image: require("../../../assets/restaurantsHome/card3.jpg"),
    name: "Kacchi Bhai - Mirpur 10",
    rating: 3,
    requiredTime: "15-20mins",
    howCostly: "$$$",
    category: "hamburger",
  },
  {
    id: "04",
    image: require("../../../assets/restaurantsHome/card4.jpg"),
    name: "Food Engineering",
    rating: 4,
    requiredTime: "25-30mins",
    howCostly: "$$",
    category: "pizza",
  },
  {
    id: "05",
    image: require("../../../assets/restaurantsHome/card5.jpg"),
    name: "Food Chemistry",
    rating: 5,
    requiredTime: "15-20mins",
    howCostly: "$",
    category: "hamburger",
  },

  {
    id: "06",
    image: require("../../../assets/restaurantsHome/card6.jpg"),
    name: "Kababwala - Mirpur 60 feet",
    rating: 3,
    requiredTime: "25-30mins",
    howCostly: "$$$",
    category: "pizza",
  },
  {
    id: "07",
    image: require("../../../assets/restaurantsHome/card7.jpg"),
    name: "Mithai - Shewrapara",
    rating: 4,
    requiredTime: "10-15mins",
    howCostly: "$$",
    category: "hamburger",
  },
  {
    id: "08",
    image: require("../../../assets/restaurantsHome/card8.jpg"),
    name: "Mr. Cooker's - Shewrapara",
    rating: 5,
    requiredTime: "15-20mins",
    howCostly: "$",
    category: "pizza",
  },
  {
    id: "09",
    image: require("../../../assets/restaurantsHome/card9.jpg"),
    name: "Cooper's - Shewrapara",
    rating: 3,
    requiredTime: "25-30mins",
    howCostly: "$$$",
    category: "hamburger",
  },
  {
    id: "10",
    image: require("../../../assets/restaurantsHome/card10.jpg"),
    name: "Cafe Kacha Langka",
    rating: 4,
    requiredTime: "15-20mins",
    howCostly: "$$",
    category: "pizza",
  },
];

export default homeRestaurantsData;

//   donut,
//   drink,
//   fries,
//   hamburger,
//   hotdog,
//   noodle,
//   pizza,
//   ricebowl,
//   salad,
//   sushi,
