export const GET_RESTAUTANTS = "GET_RESTAURANTS";
export const GET_RESTAUTANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS";
export const GET_RESTAUTANTS_ERROR = "GET_RESTAURANTS_ERROR";

export const GET_SINGLE_RESTAUTANT = "GET_SINGLE_RESTAURANT";
export const GET_SINGLE_RESTAUTANT_SUCCESS = "GET_SINGLE_RESTAURANT_SUCCESS";
export const GET_SINGLE_RESTAUTANT_ERROR = "GET_SINGLE_RESTAURANT_ERROR";
